(()=>{
const config=window.SAFWAH_AI_CONFIG||{},panel=document.querySelector('#ai-panel'),log=document.querySelector('#ai-log'),input=document.querySelector('#ai-question'),status=document.querySelector('#ai-status'),form=document.querySelector('#ai-form'),send=document.querySelector('#ai-send'),history=[];
const tr=(a,e)=>document.documentElement.lang==='ar'?a:e;
let busy=false,active=false;try{active=config.enabled===true&&new URL(config.endpoint).protocol==='https:';}catch{}
function state(){if(!active){document.querySelector('#ai-open').hidden=true;panel.hidden=true;return;}input.disabled=!active;send.disabled=!active||busy;status.textContent=active?tr('أجوبة آلية مع مصادر؛ راجع الجهة المختصة قبل القرار.','AI answers with sources; verify decisions with the competent authority.'):tr('المساعد غير مفعّل بعد. تواصل مع فريق صفوة الاستثمارية للإجابة عن سؤالك.','The assistant is not active yet. Contact the Safwah Investment team for help.');}
function append(role,text,sources=[]){const box=document.createElement('article');box.className='chat-message '+role;const label=document.createElement('strong');label.textContent=role==='user'?tr('أنت','You'):tr('مساعد صفوة الاستثمارية AI','Safwah Investment AI');const p=document.createElement('p');p.textContent=text;box.append(label,p);for(const s of sources){try{const url=new URL(s.url);if(url.protocol!=='https:')continue;const a=document.createElement('a');a.href=url.href;a.textContent=s.title||url.hostname;a.target='_blank';a.rel='noopener noreferrer';box.append(a);}catch{}}log.append(box);box.scrollIntoView({block:'nearest'});}
document.querySelector('#ai-open').addEventListener('click',()=>{panel.hidden=false;document.querySelector('#ai-open').setAttribute('aria-expanded','true');state();document.querySelector('#ai-close').focus();});
document.querySelector('#ai-close').addEventListener('click',()=>{panel.hidden=true;document.querySelector('#ai-open').setAttribute('aria-expanded','false');document.querySelector('#ai-open').focus();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)document.querySelector('#ai-close').click();});
document.querySelector('#language').addEventListener('click',()=>{if(!busy)state();});
form.addEventListener('submit',async e=>{e.preventDefault();if(!active||busy||!form.reportValidity())return;const question=input.value.trim();if(!question)return;busy=true;send.disabled=true;input.disabled=true;append('user',question);status.textContent=tr('جارٍ البحث في المصادر الرسمية…','Checking official sources…');try{const r=await fetch(config.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,history:history.slice(-6)}),signal:AbortSignal.timeout(50000)});if(!r.ok)throw Error('unavailable');const data=await r.json();if(typeof data.answer!=='string'||!Array.isArray(data.sources))throw Error('invalid');append('assistant',data.answer,data.sources);history.push({role:'user',content:question},{role:'assistant',content:data.answer.slice(0,4000)});input.value='';status.textContent=tr('إجابة آلية؛ تحقق من المصادر قبل اتخاذ القرار.','AI-generated answer; verify the sources before deciding.');}catch{status.textContent=tr('تعذر الحصول على رد موثق الآن. حاول لاحقًا أو تواصل مع صفوة الاستثمارية.','A sourced answer is unavailable now. Try later or contact Safwah Investment.');}finally{busy=false;send.disabled=false;input.disabled=false;input.focus();}});state();
})();
