let records=[],token='',visible=[],editing=null;const $=s=>document.querySelector(s), f=$('#form');const fmt=n=>(n/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const d=await financeState();records=d.records;token=d.token;render()}
function render(){
 visible=selectRecords(records,{query:$('#search').value,month:$('#month').value,kind:$('#filter').value,review:$('#review').checked,settlement:$('#settlement').value,sort:$('#sort').value});
 const totals=summarizeRecords(visible);
 $('#scope').textContent='المعروض: '+visible.length+' من '+records.length+' حركة · '+($('#month').value||'جميع الأشهر')+' · المؤشرات حسب التصفية الحالية';
 $('#cards').innerHTML=[['التحصيل المسجل',totals.incoming,'دفعات الإيرادات'],['الصرف المسجل',totals.outgoing,'يشمل العهد والتجهيزات'],['مستحق لك',totals.due,'إيرادات لم تُحصّل'],['مستحق عليك',totals.owed,'حركات لم تُسدّد']].map(([t,n,h])=>`<div class="card">${t}<strong dir="ltr">${fmt(n)}</strong><small>${h} · ر.س.</small></div>`).join('');
 $('#cash-summary').innerHTML=`<strong class="summary-number" dir="ltr">${fmt(totals.incoming-totals.outgoing)} <small>ر.س.</small></strong><div class="cash-lines"><span>تحصيل <b dir="ltr">${fmt(totals.incoming)}</b></span><span>صرف <b dir="ltr">${fmt(totals.outgoing)}</b></span></div>`;
 $('#review-summary').innerHTML=`<strong class="summary-number">${totals.reviewCount} <small>حركة تحتاج مراجعة</small></strong><p class="muted">إجمالي قيمتها: <b dir="ltr">${fmt(totals.reviewAmount)}</b> ر.س. · ${totals.openCount} حركة لها مبلغ متبقٍ</p>`;
 $('#review-focus').disabled=!totals.reviewCount;
 $('#count').textContent=`(${visible.length})`;
 $('#rows').innerHTML=visible.map(r=>{const paid=paidAmount(r);return `<tr><td>${esc(r.date||'تاريخ غير مذكور')}</td><td>${esc(r.description)}<small>${esc(r.party)}${r.reference?' · '+esc(r.reference):''}</small></td><td><span class="kind">${esc(r.kind)}</span></td><td class="money">${fmt(r.amount)}</td><td class="money">${fmt(paid)}</td><td class="money">${fmt(r.amount-paid)}<small>${paid===r.amount?'مسدد بالكامل':paid?'مسدد جزئيًا':'غير مسدد'}</small></td><td><span class="tag ${r.reviewed?'ok':''}">${r.reviewed?'تمت المراجعة':'تحتاج مراجعة'}</span></td><td><button class="secondary edit" data-id="${esc(r.id)}" aria-label="فتح الحركة: ${esc(r.description)}">فتح</button></td></tr>`}).join('')||`<tr><td colspan="8" class="empty"><strong>${records.length?'لا توجد حركات تطابق التصفية':'ابدأ بتسجيل أول حركة'}</strong><p>${records.length?'غيّر البحث أو ألغِ التصفية لعرض الحركات.':'أضف إيرادًا أو مصروفًا، أو استورد نسخة احتياطية من سجلاتك.'}</p><button type="button" id="empty-action">${records.length?'إلغاء التصفية':'＋ إضافة حركة'}</button></td></tr>`;
 document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openRecord(records.find(r=>r.id===b.dataset.id)));
 if($('#empty-action'))$('#empty-action').onclick=()=>records.length?$('#clear').click():openRecord();
}

function payment(p={amount:0,date:''}){const el=document.createElement('div');el.className='pay';el.dataset.source=p.source||'manual';el.innerHTML=`<input type="number" step="0.01" min="0.01" placeholder="المبلغ" aria-label="مبلغ الدفعة" value="${p.amount?p.amount/100:''}" required><input type="date" aria-label="تاريخ السداد" value="${esc(p.date)}"><button type="button" class="secondary">حذف الدفعة</button>`;el.querySelector('button').onclick=()=>el.remove();$('#payments').append(el)}
function openRecord(r,payrollKind){editing=r||null;f.reset();$('#error').textContent='';$('#file').value='';$('#title').textContent=r?'مراجعة الحركة':'إضافة حركة';for(const k of ['id','description','party','reference','notes','date'])f.elements[k].value=r?.[k]||'';f.elements.kind.value=r?.kind||'مصروف';if(!r)f.elements.date.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);f.elements.amount.value=r?r.amount/100:'';f.elements.reviewed.value=String(r?.reviewed||false);$('#payments').innerHTML='';(r?.payments||[]).forEach(payment);$('#attachments').innerHTML=(r?.attachments||[]).map(a=>`<a href="/file/${encodeURIComponent(a.id)}" target="_blank">📎 ${esc(a.name)}</a>`).join('')+(r?.source?'<a href="/file/source" target="_blank">كشف المحاسب الأصلي — '+esc(r.source)+'</a>':'');if(payrollKind){f.elements.kind.value=payrollKind;f.elements.description.value=payrollKind;}$('#editor').showModal()}
async function post(path,data){return financePost(path,data)}
f.onsubmit=async e=>{e.preventDefault();$('#save').disabled=true;$('#error').textContent='';try{const file=$('#file').files[0];if(file&&file.size>20000000)throw Error('الملف أكبر من 20 ميجابايت');const p=Object.fromEntries(new FormData(f));p.reviewed=p.reviewed==='true';p.payments=[...document.querySelectorAll('.pay')].map(el=>({amount:el.querySelectorAll('input')[0].value,date:el.querySelectorAll('input')[1].value,source:el.dataset.source}));const d=await post('/api/save',p);f.elements.id.value=d.record.id;editing=d.record;if(file){try{const content=await new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve(rd.result.split(',')[1]);rd.onerror=reject;rd.readAsDataURL(file)});await post('/api/upload',{id:d.record.id,name:file.name,content})}catch(err){await load();throw Error('تم حفظ الحركة، لكن لم يُحفظ المرفق: '+err.message)}}await load();$('#editor').close();$('#toast').textContent=cloudEnabled?'تم الحفظ المركزي':'تم الحفظ على جهازك';$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3000)}catch(err){$('#error').textContent=err.message}finally{$('#save').disabled=false}};
document.querySelectorAll('.payroll-new').forEach(button=>button.onclick=()=>{openRecord(null,button.dataset.kind);});
$('#review-focus').onclick=()=>{$('#review').checked=true;render();$('.panel').scrollIntoView({behavior:'smooth'})};
$('#new').onclick=()=>openRecord();$('#close').onclick=()=>$('#editor').close();$('#addpay').onclick=()=>payment();for(const s of ['#search','#month','#filter','#review','#settlement','#sort'])$(s).oninput=render;$('#clear').onclick=()=>{$('#search').value='';$('#month').value='';$('#filter').value='';$('#review').checked=false;$('#settlement').value='';$('#sort').value='newest';render()};$('#print').onclick=()=>window.print();$('#csv').onclick=()=>{const rows=[['التاريخ','البيان','الجهة','التصنيف','المبلغ','السداد','المتبقي','المرجع','ملاحظات','المراجعة'],...visible.map(r=>{const p=paidAmount(r);return[r.date,r.description,r.party,r.kind,r.amount/100,p/100,(r.amount-p)/100,r.reference,r.notes,r.reviewed?'تمت المراجعة':'تحتاج مراجعة']})];downloadBlob(excelWorkbook(rows),'safwah-ledger.xlsx')};if(!cloudEnabled)load().catch(e=>{$('#rows').textContent=e.message});

