// Browser edition: all private records and attachments remain in this browser.
const localServer=['127.0.0.1','localhost'].includes(location.hostname);
let browserDB;
async function openDB(){if(browserDB)return browserDB;browserDB=await new Promise((resolve,reject)=>{const r=indexedDB.open('safwah-finance-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return browserDB}
async function readStore(key){const d=await openDB();return new Promise((resolve,reject)=>{const r=d.transaction('data').objectStore('data').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function writeStore(key,value){const d=await openDB();return new Promise((resolve,reject)=>{const tx=d.transaction('data','readwrite');tx.objectStore('data').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
function cents(v){const s=String(v);if(!/^\d+(\.\d{1,2})?$/.test(s)||Number(s)>1e9)throw Error('أدخل مبلغًا صحيحًا بمنزلتين عشريتين كحد أقصى');return Math.round(Number(s)*100)}
async function financeState(){if(localServer){const r=await fetch('/api/state');if(!r.ok)throw Error('تعذر تحميل البيانات');return r.json()}return {records:(await readStore('records'))||[],token:'browser'}}
async function financePost(path,p){if(localServer){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Token':token},body:JSON.stringify(p)});const d=await r.json();if(!r.ok)throw Error(d.error);return d}const list=(await readStore('records'))||[];let r=list.find(x=>x.id===p.id);if(path==='/api/save'){if(!p.description.trim())throw Error('أدخل البيان');const amount=cents(p.amount);if(!amount)throw Error('المبلغ يجب أن يكون أكبر من صفر');const payments=p.payments.map(x=>{if(!x.date)throw Error('حدد تاريخ السداد');const amount=cents(x.amount);if(!amount)throw Error('أدخل مبلغ الدفعة');return {...x,amount}});if(payments.reduce((s,x)=>s+x.amount,0)>amount)throw Error('السداد يتجاوز قيمة الحركة');const next={...r,...p,id:r?.id||crypto.randomUUID(),amount,payments,attachments:r?.attachments||[]};if(r)list[list.indexOf(r)]=next;else list.push(next);r=next;await writeStore('records',list)}else{if(!r)throw Error('احفظ الحركة أولًا');if(!/^(JVBERi0|iVBORw0KGgo|\/9j\/)/.test(p.content))throw Error('المسموح PDF وPNG وJPEG');const id=crypto.randomUUID();await writeStore('file:'+id,{name:p.name,content:p.content});r.attachments.push({id,name:p.name});await writeStore('records',list)}return {ok:true,record:r}}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('click',async e=>{const a=e.target.closest('a');if(localServer||Boolean(window.SAFWAH_CLOUD?.url||window.SAFWAH_CLOUD?.publishableKey)||!a)return;const href=a.getAttribute('href');if(href==='/backup'){e.preventDefault();try{const records=(await readStore('records'))||[];const files={};for(const r of records)for(const f of r.attachments)files[f.id]=await readStore('file:'+f.id);downloadBlob(new Blob([JSON.stringify({format:'safwah-finance-v1',records,files})],{type:'application/json'}),'safwah-backup-'+new Date().toISOString().slice(0,10)+'.json')}catch(err){alert('تعذر إنشاء النسخة: '+err.message)}}else if(href?.startsWith('/file/')){e.preventDefault();const file=await readStore('file:'+href.slice(6));if(!file){alert('المرفق غير موجود في هذا المتصفح');return}const raw=atob(file.content),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));downloadBlob(new Blob([bytes]),file.name)}});
if(!localServer&&!Boolean(window.SAFWAH_CLOUD?.url||window.SAFWAH_CLOUD?.publishableKey)){document.querySelector('aside').textContent='دفتر خاص بهذا المتصفح: لا تُرفع الفواتير إلى GitHub. البيانات لا تتزامن بين الأجهزة، وقد تُفقد عند مسح بيانات المتصفح. نزّل نسخة احتياطية بعد العمل. لا تضع بيانات حساسة على جهاز مشترك.';document.querySelector('.pill').textContent='● الحفظ داخل هذا المتصفح';document.querySelector('a[href="/file/source"]').remove();const restore=document.createElement('button');restore.type='button';restore.className='secondary';restore.textContent='استيراد نسخة احتياطية';document.querySelector('.panelhead>div').append(restore);restore.onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>100000000)throw Error('النسخة أكبر من 100 ميجابايت');const backup=JSON.parse(await file.text());if(backup.format!=='safwah-finance-v1'||!Array.isArray(backup.records)||!backup.files)throw Error('ملف غير صالح');const current=(await readStore('records'))||[];const ids=new Set(current.map(r=>r.id));const imported=backup.records.filter(r=>!ids.has(r.id));for(const r of imported){if(typeof r.id!=='string'||!Number.isSafeInteger(r.amount)||r.amount<=0||!Array.isArray(r.payments)||!Array.isArray(r.attachments)||typeof r.date!=='string')throw Error('بيانات غير صالحة');for(const p of r.payments)if(!Number.isSafeInteger(p.amount)||p.amount<=0)throw Error('دفعة غير صالحة');if(r.payments.reduce((s,p)=>s+p.amount,0)>r.amount)throw Error('سداد غير صالح');for(const f of r.attachments){const data=backup.files[f.id];if(!data||typeof data.content!=='string'||!/^(JVBERi0|iVBORw0KGgo|\/9j\/)/.test(data.content))throw Error('مرفق غير صالح')}}const d=await openDB();await new Promise((resolve,reject)=>{const tx=d.transaction('data','readwrite'),store=tx.objectStore('data');for(const r of imported)for(const f of r.attachments)store.put(backup.files[f.id],'file:'+f.id);store.put([...current,...imported],'records');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});await load();alert('تم استيراد '+imported.length+' حركة جديدة. السجلات الموجودة لم تتغير.')}catch(err){alert('لم يتم الاستيراد: '+err.message)}};input.click()}}

