const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
let calls=[],reply=[],events=[];
const nodes=new Map();
function node(selector){if(!nodes.has(selector))nodes.set(selector,{hidden:false,disabled:false,textContent:'',innerHTML:'',value:'viewer',querySelectorAll(){return []},querySelector(){return node(selector+' child')},close(){},closest(){return node(selector+' label')}});return nodes.get(selector)}
const fields=[node('field-a'),node('field-b')],paymentButtons=[node('payment-delete')],rowButtons=[node('edit-row')];
const form=node('#auth-form');form.elements={email:{value:'new@example.com'}};form.reportValidity=()=>true;form.querySelectorAll=()=>[node('send-login'),node('send-request')];
const document={querySelector:node,querySelectorAll:selector=>selector==='#form input,#form select,#form textarea'?fields:selector==='#payments button'?paymentButtons:selector==='.edit'?rowButtons:[]};
const context={records:[],visible:[],editing:null,document,cents:v=>Math.round(Number(v)*100),atob,Uint8Array,window:{SAFWAH_CLOUD:{},location:{hash:'',pathname:'/finance/',search:'',origin:'https://site.example'},history:{replaceState(_state,_title,url){events.push('clear');context.window.location.hash='';assert.equal(url,'/finance/')}}},fetch:async(url,options)=>{events.push('fetch');calls.push({url,options});const response=reply.shift();if(!response)throw Error('Unexpected request');return {ok:response.ok!==false,status:response.status||200,json:async()=>response.body}},Date,Map,Boolean,Error,URLSearchParams,encodeURIComponent,JSON,crypto:require('node:crypto').webcrypto};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../cloud.js'),'utf8'),context);
vm.runInContext("cloudConfig.url='https://example.supabase.co';cloudConfig.publishableKey='public-key';async function load(){const state=await cloudState();records=state.records}",context);
const user={id:'verified-user',email:'reader@example.com',email_confirmed_at:'2026-10-04T10:00:00Z'};
function callback(){context.window.location.hash='#access_token=test-token&refresh_token=test-refresh&expires_in=3600&type=magiclink';events=[];calls=[]}
(async()=>{
 callback();reply=[{body:user},{body:[]},{body:[]}];
 await vm.runInContext('cloudHandleCallback()',context);
 assert.deepEqual(events.slice(0,2),['clear','fetch']);
 assert.ok(calls[0].url.endsWith('/auth/v1/user'));
 assert.equal(calls[0].options.headers.Authorization,'Bearer test-token');
 assert.equal(vm.runInContext('cloudSession.user.id',context),'verified-user');
 assert.ok(calls.every(call=>!call.url.includes('finance_records')));
 assert.equal(node('#ledger').hidden,true);assert.match(node('#auth-status').textContent,/اعتماد مالك المشروع/);
 callback();reply=[{ok:false,status:401,body:{message:'invalid token'}}];
 await vm.runInContext('cloudHandleCallback()',context);
 assert.equal(calls.length,1);assert.equal(context.window.location.hash,'');assert.equal(vm.runInContext('cloudSession',context),null);
 callback();reply=[{body:{...user,email_confirmed_at:null}}];
 await vm.runInContext('cloudHandleCallback()',context);
 assert.equal(calls.length,1);assert.equal(vm.runInContext('cloudSession',context),null);
 callback();reply=[{body:user},{body:[{access_role:'viewer'}]},{body:[{id:'record-a',revision:1,data:{description:'حركة',amount:100,attachments:[]}}]}];
 await vm.runInContext('cloudHandleCallback()',context);
 assert.equal(node('#ledger').hidden,false);assert.equal(node('#approval-panel').hidden,true);
 assert.equal(node('#new').hidden,true);assert.equal(node('.payroll-actions').hidden,true);assert.equal(node('#migrate-local').hidden,true);
 assert.equal(rowButtons[0].textContent,'عرض');
 const before=calls.length;
 await assert.rejects(vm.runInContext("cloudPost('/api/save',{})",context),/للاطلاع فقط/);
 await assert.rejects(vm.runInContext("cloudSave({},0)",context),/للاطلاع فقط/);
 await assert.rejects(vm.runInContext('cloudLoadAccessRequests()',context),/مالك المشروع فقط/);
 await assert.rejects(vm.runInContext('cloudDecideAccess({},true)',context),/مالك المشروع فقط/);
 assert.equal(calls.length,before);
 vm.runInContext('cloudReadOnlyEditor()',context);
 assert.ok(fields.every(field=>field.disabled));assert.equal(node('#save').hidden,true);assert.equal(node('#addpay').hidden,true);assert.equal(paymentButtons[0].hidden,true);
 callback();reply=[{body:{...user,email:'afalsuhaimi@gmail.com'}},{body:[]},{body:[{user_id:user.id}]},{body:[]},{body:[]}];
 await vm.runInContext('cloudHandleCallback()',context);
 assert.equal(vm.runInContext('cloudRole',context),'owner');assert.equal(node('#approval-panel').hidden,false);assert.equal(node('#new').hidden,false);
 const ownerList=calls.find(call=>call.url.endsWith('/rpc/list_finance_access_requests'));
 assert.deepEqual(JSON.parse(ownerList.options.body),{status_filter:'pending'});
 node('#request-status-filter').value='approved';calls=[];reply=[{body:[]}];await vm.runInContext('cloudLoadAccessRequests()',context);
 assert.deepEqual(JSON.parse(calls[0].options.body),{status_filter:'approved'});
 node('#request-status-filter').value='all';calls=[];reply=[{body:[]}];await vm.runInContext('cloudLoadAccessRequests()',context);
 assert.deepEqual(JSON.parse(calls[0].options.body),{status_filter:null});node('#request-status-filter').value='pending';
 context.requestRow={dataset:{requestId:'request-a'},querySelectorAll(){return [node('approve'),node('reject')]},querySelector(){return {value:'viewer'}}};
 calls=[];reply=[{body:{status:'approved',access_role:'viewer'}},{body:[]}];
 await vm.runInContext('cloudDecideAccess(requestRow,true)',context);
 assert.ok(calls[0].url.endsWith('/functions/v1/finance-access'));
 assert.equal(calls[0].options.headers.Authorization,'Bearer test-token');
 assert.deepEqual(JSON.parse(calls[0].options.body),{action:'decide',requestId:'request-a',approve:true,role:'viewer'});
 // A visitor never learns private request status. Requests and login are separate.
 vm.runInContext('cloudSession=null;cloudRole=null',context);form.elements.email.value='new@example.com';calls=[];reply=[{body:{accepted:true}}];
 await vm.runInContext("cloudSendAuthRequest('request')",context);
 assert.equal(calls.length,1);assert.ok(calls[0].url.endsWith('/functions/v1/finance-access'));
 assert.deepEqual(JSON.parse(calls[0].options.body),{action:'request',email:'new@example.com'});
 form.elements.email.value='new@example.com';calls=[];
 let finish;context.fetch=(url,options)=>{calls.push({url,options});return new Promise(resolve=>{finish=()=>resolve({ok:true,status:200,json:async()=>({})})})};
 const sending=vm.runInContext("cloudSendAuthRequest('login')",context);
 await vm.runInContext("cloudSendAuthRequest('request')",context);
 assert.equal(calls.length,1);assert.ok(form.querySelectorAll().every(button=>button.disabled));
 assert.equal(new URL(calls[0].url).searchParams.get('redirect_to'),'https://site.example/finance/');
 assert.deepEqual(JSON.parse(calls[0].options.body),{email:'new@example.com',create_user:true});
 finish();await sending;assert.ok(form.querySelectorAll().every(button=>!button.disabled));
 const page=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');assert.ok(!/type="password"/.test(page));
 console.log('PASS: callback tokens clear before requests; Auth verifies user before membership; invalid/unconfirmed tokens never expose ledger');
 console.log('PASS: pending confirmed email cannot read records; viewers can read but cannot mutate even through direct API adapter calls');
 console.log('PASS: owner-only approval list, viewer controls/read-only dialog, email-only single-flight OTP and generic access request');
})().catch(error=>{console.error(error);process.exitCode=1});
