const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
let calls=[],reply=[];
const context={records:[],cents:v=>Math.round(Number(v)*100),atob,Uint8Array,window:{SAFWAH_CLOUD:{}},fetch:async(url,options)=>{calls.push({url,options});const x=reply.shift();if(!x)throw Error('Unexpected request');return {ok:x.ok!==false,status:x.status||200,json:async()=>x.body}},Date,Map,Boolean,Error,encodeURIComponent,JSON,crypto:require('node:crypto').webcrypto};
vm.createContext(context);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../cloud.js'),'utf8'),context);
vm.runInContext("cloudConfig.url='https://example.supabase.co';cloudConfig.publishableKey='public-key';cloudSession={access_token:'user-token',expires_at:Date.now()/1000+3600,user:{id:'user-id'}}",context);
(async()=>{
 reply=[{body:[]}];
 await assert.rejects(vm.runInContext('cloudState()',context),/تفعيل صلاحية المدير/);
 assert.equal(calls.length,1);assert.ok(!calls[0].url.includes('finance_records'));
 calls=[];reply=[{body:[{user_id:'user-id'}]},{body:[{id:'a',revision:2,data:{description:'صفوة',amount:100}}]}];
 const state=await vm.runInContext('cloudState()',context);
 assert.equal(state.records[0].description,'صفوة');assert.equal(calls[1].options.headers.Authorization,'Bearer user-token');
 reply=[{ok:false,status:400,body:{message:'STALE_RECORD'}}];
 await assert.rejects(vm.runInContext("cloudSave({id:'a'},2)",context),/جهاز آخر/);
 reply=[{body:3}];await vm.runInContext("cloudSave({id:'a'},2)",context);
 assert.equal(vm.runInContext("cloudRevisions.get('a')",context),3);
 context.records=[];calls=[];reply=[{body:1},{body:{}},{body:2}];
 const added=await vm.runInContext("cloudPost('/api/save',{description:'فاتورة جديدة',amount:'100.00',kind:'مصروف',payments:[],reviewed:false,account:'كهرباء ومياه'})",context);
 context.newId=added.record.id;
 await vm.runInContext("cloudPost('/api/upload',{id:newId,name:'test.pdf',content:'JVBERi0xLjQ='})",context);
 assert.equal(context.records.length,1);
 assert.equal(context.records[0].attachments.length,1);
 assert.equal(JSON.parse(calls[2].options.body).expected_revision,1);
 context.records[0].source='كشف المحاسب.xlsx';
 calls=[];reply=[{body:3},{body:{}},{body:4}];
 await vm.runInContext("cloudPost('/api/save',{id:newId,description:'البيان المعدل',amount:'120.50',kind:'مصروف',payments:[],reviewed:true,account:'إنترنت وهاتف',notes:'ملاحظات جديدة'})",context);
 await vm.runInContext("cloudPost('/api/upload',{id:newId,name:'second.pdf',content:'JVBERi0xLjQ='})",context);
 const final=JSON.parse(calls[2].options.body).record_data;
 assert.equal(final.description,'البيان المعدل');assert.equal(final.amount,12050);assert.equal(final.reviewed,true);assert.equal(final.account,'إنترنت وهاتف');assert.equal(final.notes,'ملاحظات جديدة');assert.equal(final.attachments.length,2);assert.equal(final.source,'كشف المحاسب.xlsx');
 vm.runInContext("cloudRevisions=new Map([['a',1]])",context);
 reply=[{body:[{user_id:'user-id'}]},{body:Array.from({length:500},(_,i)=>({id:i===0?'a':'page-'+i,revision:2,data:{description:'latest'}}))},{ok:false,status:500,body:{message:'network failure'}}];
 await assert.rejects(vm.runInContext('cloudState()',context),/network failure/);
 assert.equal(vm.runInContext("cloudRevisions.get('a')",context),1);
 assert.equal(vm.runInContext("cloudRevisions.size",context),1);
 context.document={querySelector:()=>({close(){},hidden:false})};context.visible=[];context.editing=null;context.render=()=>{};
 let releaseRefresh,refreshCount=0;
 context.fetch=async url=>{if(url.includes('grant_type=refresh_token')){refreshCount++;return new Promise(resolve=>{releaseRefresh=()=>resolve({ok:true,status:200,json:async()=>({access_token:'renewed',refresh_token:'r2',expires_in:3600,user:{id:'user-id'}})})})}return {ok:true,status:200,json:async()=>[]}};
 vm.runInContext("cloudSession={access_token:'expired',refresh_token:'r1',expires_at:0,user:{id:'user-id'}}",context);
 const one=vm.runInContext("cloudRequest('/rest/v1/test')",context),two=vm.runInContext("cloudRequest('/rest/v1/test')",context);
 assert.equal(refreshCount,1);releaseRefresh();await Promise.all([one,two]);
 vm.runInContext("cloudSession={access_token:'expired',refresh_token:'r1',expires_at:0,user:{id:'user-id'}}",context);
 const pending=vm.runInContext("cloudRequest('/rest/v1/test')",context);
 const rejected=assert.rejects(pending,/تغيّرت جلسة/);
 await vm.runInContext('cloudSignOut()',context);
 assert.equal(vm.runInContext('cloudSession',context),null);
 releaseRefresh();await rejected;
 assert.equal(vm.runInContext('cloudSession',context),null);
 console.log('PASS: unapproved accounts cannot request ledger, authenticated headers, revision conflicts and save response');
 console.log('PASS: new-record attachment and edited-record attachment preserve every saved field');
 console.log('PASS: interrupted multi-page refresh cannot advance revisions while leaving stale records');
 console.log('PASS: concurrent calls refresh once; late refresh never restores a signed-out session');
})().catch(e=>{console.error(e);process.exitCode=1});
