const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const id='11111111-1111-4111-8111-111111111111';
const entry={id,date:'2026-10-06',description:'قيد عربي',reference:'=SUM(A1)',entryType:'standard',sourceRecordId:null,reversalOf:null,lines:[{account:'1101',debit:10001,credit:0},{account:'4101',debit:0,credit:10001}]};
let calls=[],responses=[],stored=[];
const context={window:{addEventListener(){}},cloudEnabled:true,cloudSession:null,cloudSessionEpoch:0,cloudCanWrite(){return Boolean(context.cloudSession?.user?.id)},cloudRequest:async(url,options)=>{calls.push({url,options});const response=responses.shift();return typeof response==='function'?response():response},readStore:async()=>stored,records:[],Date,JSON,encodeURIComponent,Error,Map,Set,BigInt,Number};
vm.createContext(context);
for(const file of ['journal.js','journal-store.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);
context.testEntry=entry;
(async()=>{
 await assert.rejects(vm.runInContext('journalState()',context),/مساحتك/);
 await assert.rejects(vm.runInContext('journalPost(testEntry)',context),/مساحتك/);assert.equal(calls.length,0);
 context.cloudSession={user:{id:'user-a'}};
 responses=[[{id,data:entry,posted_at:'2026-10-06T10:00:00Z'}]];
 const loaded=await vm.runInContext('journalState()',context);
 assert.equal(loaded[0].description,'قيد عربي');assert.equal(loaded[0].postedAt,'2026-10-06T10:00:00Z');
 assert.ok(calls[0].url.includes('owner_id=eq.user-a'));assert.ok(calls[0].options.headers.Range==='0-499');
 responses=[{id,data:entry,posted_at:'2026-10-06T10:00:00Z'}];
 await vm.runInContext('journalPost(testEntry)',context);
 assert.equal(calls[1].url,'/rest/v1/rpc/post_finance_journal');assert.equal(JSON.parse(calls[1].options.body).entry.id,id);
 responses=[{id:'different',data:entry}];await assert.rejects(vm.runInContext('journalPost(testEntry)',context),/يتأكد/);
 responses=[()=>{context.cloudSessionEpoch++;context.cloudSession={user:{id:'user-b'}};return [{id,data:entry}]}];
 await assert.rejects(vm.runInContext('journalState()',context),/تغيّرت/);
 responses=[[{id,data:{...entry,lines:[{account:'1101',debit:1,credit:0},{account:'4101',debit:0,credit:2}]}}]];
 await assert.rejects(vm.runInContext('journalState()',context));
 context.cloudEnabled=false;stored=[{...entry,postedAt:'2026-10-06T10:00:00Z'}];
 assert.equal((await vm.runInContext('journalState()',context))[0].id,id);
 const reversal={...entry,id:'22222222-2222-4222-8222-222222222222',description:'عكس قيد',entryType:'reversal',reversalOf:id,lines:entry.lines.map(l=>({account:l.account,debit:l.credit,credit:l.debit}))};
 context.original=entry;context.reversal=reversal;
 vm.runInContext('journalValidateLinks(reversal,[original],[])',context);
 assert.throws(()=>vm.runInContext('journalValidateLinks(reversal,[original,reversal],[])',context),/سبق عكس/);
 context.badReversal={...reversal,lines:entry.lines};
 assert.throws(()=>vm.runInContext('journalValidateLinks(badReversal,[original],[])',context),/يعكس/);
 context.imported=[reversal,entry];context.current=[];
 assert.equal(vm.runInContext('journalValidateBackup(imported,current,[])',context).length,2);
 context.imported=[{...entry,sourceRecordId:'33333333-3333-4333-8333-333333333333'}];
 assert.throws(()=>vm.runInContext('journalValidateBackup(imported,current,[])',context),/غير موجودة/);
 assert.equal(JSON.stringify(entry.lines),JSON.stringify(context.testEntry.lines));
 console.log('PASS: private journal session/owner filter, RPC normalization, stale-session isolation, malformed data failure, reversal and backup references');
})().catch(e=>{console.error(e);process.exitCode=1});

